export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const FETCH_USERS = "FETCH_USERS";
export const FETCH_USERS_ERROR = "FETCH_USERS_ERROR";
export const FETCH_ALL_PRODUCTS_LIST = "FETCH_ALL_PRODUCTS_LIST";
export const FETCH_ALL_PRODUCTS_LIST_ERROR = "FETCH_ALL_PRODUCTS_LIST_ERROR";

export const FETCH_ALL_FEATURED_PRODUCTS_LIST =
  "FETCH_ALL_FEATURED_PRODUCTS_LIST";

export const FETCH_ALL_FEATURED_PRODUCTS_LIST_ERROR =
  "FETCH_ALL_FEATURED_PRODUCTS_LIST_ERROR";

export const FETCH_FEATURED_PRODUCTS_DETAILS =
  "FETCH_FEATURED_PRODUCTS_DETAILS";

export const FETCH_FEATURED_PRODUCTS_DETAILS_ERROR =
  "FETCH_FEATURED_PRODUCTS_DETAILS_ERROR";

export const FILTER_FEATURED_PRODUCTS = "FILTER_FEATURED_PRODUCTS";
