# Generated by Django 3.0.7 on 2020-06-26 10:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.BooleanField(blank=True, default=False, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^(\\+\\d{1,3})?,?\\s?\\d{8,13}')])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product_price', models.IntegerField()),
                ('negotiable', models.BooleanField(blank=True, default=True, null=True)),
                ('used', models.BooleanField(default=False)),
                ('used_duration', models.PositiveIntegerField(blank=True, null=True)),
                ('division', models.CharField(blank=True, max_length=10, null=True)),
                ('zilla', models.CharField(blank=True, max_length=10, null=True)),
                ('thana', models.CharField(blank=True, max_length=10, null=True)),
                ('zip_code', models.IntegerField()),
                ('is_sold', models.BooleanField(blank=True, default=False, null=True)),
                ('category', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Member')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'All Products',
                'ordering': ['-timestamp'],
            },
        ),
    ]
