# Generated by Django 3.0.7 on 2020-06-26 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200626_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Category'),
        ),
    ]
