# Generated by Django 3.0.7 on 2020-06-26 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200626_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['id'], 'verbose_name': 'Product', 'verbose_name_plural': 'All Products'},
        ),
    ]
